[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "https://toromoveit.com/*"
  to = "https://toromovers.net/?utm_source=toromoveit&utm_medium=redirect"
  status = 301
  force = true

[[redirects]]
  from = "https://www.toromoveit.com/*"
  to = "https://toromovers.net/?utm_source=toromoveit&utm_medium=redirect"
  status = 301
  force = true
